trigger:
- master

pool:
  name: Default

variables:
  AWS_ACCESS_KEY_ID: '自分ACCESS_KEY_ID'
  AWS_SECRET_ACCESS_KEY: '自分SECRET_ACCESS_KEY'

stages:
- stage: Terraform
  displayName: "Terraform Deployment"
  jobs:
  - job: Terraform_Job
    displayName: "Terraform Job"
    steps:
    - checkout: self  # 拉取代码库
    - script: |
        terraform init -reconfigure
      displayName: "Terraform Init with Partial Local Plugins"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    # Terraform Plan
    - script: |
        terraform plan
      displayName: "Terraform Plan"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
